version: "3"
services:
  client:
    container_name: vite-heroes
    tty: true
    stdin_open: true
    build: ./
    ports:
      - 3000:3000
    volumes:
    - ./:/usr/src/app
    - /usr/src/app/node_modules/